### ISSUE TITLE
collecting ethtool statistics on any port

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap-plugin-collector-ethtool#13]
Hi,
is it possible to define that the metrics for ethtool are required from all existing devices?
to use for example the following notation:
                "/intel/net/ixgbe/_/nic/alloc_rx_buff_failed": {},
                "/intel/net/ixgbe/_/nic/alloc_rx_page_failed": {},
                "/intel/net/ixgbe/*/nic/broadcast": {}

instead of specifing each device seperately.

Thanks,
Shirley.

**Comment by nanliu** [comment]
What version of snap are you using? This should be possible with the * wildcard specification.

**Comment by IRCody** [comment]
@imvisiontech: Have you had a chance to test with the * wildcard?

**Comment by nanliu** [comment]
Closing this issue since this should be possible. Please feel free to reopen this issue if you have any new updates.
