### ISSUE TITLE
Unable to load ethtool plugin

### ISSUE THREAD

**Issue by kamsz** [intelsdi-x/snap-plugin-collector-ethtool#8]
@lmroz asked for stderr and ethtool results:

[snap-plugin-collector-ethtool.stderr.txt](https://github.com/intelsdi-x/snap-plugin-collector-ethtool/files/186040/snap-plugin-collector-ethtool.stderr.txt)

[ethtool.txt](https://github.com/intelsdi-x/snap-plugin-collector-ethtool/files/186055/ethtool.txt)

root@node-1:~# ethtool -i eth0
driver: ixgbe
version: 3.15.1-k
firmware-version: 0x80000647
bus-info: 0000:01:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

root@node-1:~# ethtool -i eth1
driver: ixgbe
version: 3.15.1-k
firmware-version: 0x80000647
bus-info: 0000:01:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

**Comment by andrzej-k** [comment]
Experimental version of the fix can be found on master at https://github.com/lmroz/snap-plugin-collector-ethtool

**Comment by kamsz** [comment]
@andrzej-k @lmroz @IzabellaRaulin I've tested it and the proposed fix works.

**Comment by IzabellaRaulin** [comment]
Great! :)

**Comment by lmroz** [comment]
> Experimental version of the fix can be found on master at https://github.com/lmroz/snap-plugin-collector-ethtool

I removed this fork because it got disconnected on github from main repo, but submitted proper fix as PR.
@kamsz Could you test this one too in your setup? :)
